### ISSUE TITLE
Update to the latest version of Emscripten with upstream LLVM backend

### ISSUE THREAD

**Issue by guster32** [OGRECave/ogre#1697]
#### System Information
- Ogre Version: 1.12.8 
- Operating System / Platform: OSX
- RenderSystem: GLES2RenderSystem

#### Detailled description
Latest version of emscripten has several fixes including handling of fullscreen see  [changelog](https://github.com/emscripten-core/emscripten/blob/master/ChangeLog.md) not to mention it now uses LLVM backend. [emscripten-llvm-wasm](https://v8.dev/blog/emscripten-llvm-wasm) which has several benefits. I am not familiar with the code base so I am unsure what it entails add support for the newer versions of emscripten. 

#### Browser Console.
Looking at the console logs of [EmscriptenDemo](https://ogrecave.github.io/ogre/emscripten/) as compared to the demo compiled using 2.0.1 it seems as if the problem may be on the RenderSystem base class using emsscripten version 2.0.1
Working Demo:
```
GLES2RenderSystem::_createRenderWindow "OGRE Emscripten Sample", 800x600 windowed  miscParams: FSAA=2 currentGLContext=true displayFrequency=N/A gamma=No vsync=Yes 
(index):1237 GL_VERSION = 2.0.0.0
(index):1237 GL_VENDOR = WebKit
(index):1237 GL_RENDERER = WebKit WebGL
(index):1237 
```

Failing Demo with latest emscripten:
```
RenderSystem::_createRenderWindow "OGRE Emscripten Sample", 800x600 windowed  miscParams: FSAA=0 displayFrequency=N/A gamma=No vsync=Yes 
EmscriptenSample.html:1 exception thrown: SyntaxError: Failed to execute 'querySelector' on 'Document': '0' is not a valid selector.,Error: Failed to execute 'querySelector' on 'Document': '0' is not a valid selector.
    at findEventTarget (http://localhost:8000/EmscriptenSample.js:1:152757)
    at __registerWebGlEventCallback (http://localhost:8000/EmscriptenSample.js:1:212626)
    at _emscripten_set_webglcontextlost_callback_on_thread (http://localhost:8000/EmscriptenSample.js:1:212927)
    at http://localhost:8000/EmscriptenSample.wasm:wasm-function[6519]:0x1e6f2a
    at http://localhost:8000/EmscriptenSample.wasm:wasm-function[6515]:0x1e6ce9
    at http://localhost:8000/EmscriptenSample.wasm:wasm-function[6329]:0x1db4bb
    at http://localhost:8000/EmscriptenSample.wasm:wasm-function[3365]:0xc4236
    at http://localhost:8000/EmscriptenSample.wasm:wasm-function[613]:0x1fa4b
    at http://localhost:8000/EmscriptenSample.wasm:wasm-function[435]:0x11dd7
    at http://localhost:8000/EmscriptenSample.wasm:wasm-function[311]:0xa52f
printErr @ EmscriptenSample.html:1
```

**Comment by guster32** [comment]
On both versions I can see that that the render system get correctly identified and added..:
```
Installing plugin: OpenGL ES 2.0 RenderSystem
(index):1237 OpenGL ES 2.x Rendering Subsystem created.
(index):1237 Plugin successfully installed
```

**Comment by guster32** [comment]
Here is the full Log with the latest version of emscripten:
```
Creating resource group General
Creating resource group OgreInternal
Creating resource group OgreAutodetect
SceneManagerFactory for type 'DefaultSceneManager' registered.
Registering ResourceManager for type Material
Registering ResourceManager for type Mesh
Registering ResourceManager for type Skeleton
MovableObjectFactory for type 'ParticleSystem' registered.
ArchiveFactory for archive type FileSystem registered.
ArchiveFactory for archive type Zip registered.
ArchiveFactory for archive type EmbeddedZip registered.
DDS codec registering
PVRTC codec registering
ETC codec registering
Registering ResourceManager for type HighLevelGpuProgram
Registering ResourceManager for type Compositor
MovableObjectFactory for type 'Entity' registered.
MovableObjectFactory for type 'Light' registered.
MovableObjectFactory for type 'BillboardSet' registered.
MovableObjectFactory for type 'ManualObject' registered.
MovableObjectFactory for type 'BillboardChain' registered.
MovableObjectFactory for type 'RibbonTrail' registered.
*-*-* OGRE Initialising
*-*-* Version 1.12.8 (Rhagorthua)
Installing plugin: OpenGL ES 2.0 RenderSystem
OpenGL ES 2.x Rendering Subsystem created.
Plugin successfully installed
Installing plugin: Octree Scene Manager
Plugin successfully installed
Installing plugin: ParticleFX
Particle Emitter Type 'Point' registered
Particle Emitter Type 'Box' registered
Particle Emitter Type 'Ellipsoid' registered
Particle Emitter Type 'Cylinder' registered
Particle Emitter Type 'Ring' registered
Particle Emitter Type 'HollowEllipsoid' registered
Particle Affector Type 'LinearForce' registered
Particle Affector Type 'ColourFader' registered
Particle Affector Type 'ColourFader2' registered
Particle Affector Type 'ColourImage' registered
Particle Affector Type 'ColourInterpolator' registered
Particle Affector Type 'Scaler' registered
Particle Affector Type 'Rotator' registered
Particle Affector Type 'DirectionRandomiser' registered
Particle Affector Type 'DeflectorPlane' registered
Plugin successfully installed
Installing plugin: STB Image Codec
stb_image - v2.23 - public domain image loader
Supported formats: jpeg,jpg,png,bmp,psd,tga,gif,pic,ppm,pgm,hdr
Plugin successfully installed
Installing plugin: DotScene Loader
Plugin successfully installed
OverlayElementFactory for type Panel registered.
OverlayElementFactory for type BorderPanel registered.
OverlayElementFactory for type TextArea registered.
Registering ResourceManager for type Font
CPU Identifier & Features
-------------------------
 *   CPU ID: Unknown
-------------------------
******************************
*** Starting EGL Subsystem ***
******************************
EGL_VERSION = 1.4 Emscripten EGL
EGL_EXTENSIONS = 
Registering ResourceManager for type Texture
RenderSystem::_createRenderWindow "OGRE Emscripten Sample", 800x600 windowed  miscParams: FSAA=0 displayFrequency=N/A gamma=No vsync=Yes 
```
