### ISSUE TITLE
Code point not found in font, when creating Tray Button

### ISSUE THREAD

**Issue by Fighter19** [OGRECave/ogre#2113]
#### System Information
- Ogre Version: 3fb7cc95e89fe27fa6f4240201a3c56e32b67007
- Operating System / Platform: Ubuntu 18.04
- RenderSystem: OpenGL3+

#### Detailled description
After upgrading my project from 1.11, I received an error message, implying that the Glyph Info has not been set yet.

This could be hot-fixed, by enabling the loading bar to show up (uncommenting the lines below)
and allowing it to execute the listener installed by "showLoadingBar"
```
	mTrayMgr = new OgreBites::TrayManager("InterfaceName", getRenderWindow(), this);
	addInputListener(mTrayMgr);

	//mTrayMgr->showLoadingBar(1, 0);
	Ogre::ResourceGroupManager::getSingleton().initialiseAllResourceGroups();
	//mTrayMgr->hideLoadingBar();

	OgreBites::Button* b = mTrayMgr->createButton(OgreBites::TL_TOPLEFT, "MyButton", "Click Me!");
```

#### Crash message
```
terminate called after throwing an instance of 'Ogre::ItemIdentityException'
  what():  ItemIdentityException: Code point 67 not found in font SdkTrays/Caption in getGlyphInfo at ./ogre/Components/Overlay/include/OgreFont.h (line 256)
```

**Comment by paroj** [comment]
please provide the full stack-trace leading to that exception

**Comment by Fighter19** [comment]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5929921 in __GI_abort () at abort.c:79
#2  0x00007ffff632d0a9 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6338506 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6338571 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff63387f5 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7bc1f6e in Ogre::ExceptionFactory::_throwException (code=code@entry=Ogre::Exception::ERR_DUPLICATE_ITEM, number=number@entry=4, 
    desc="Code point 67 not found in font SdkTrays/Caption", src="getGlyphInfo", 
    file=file@entry=0x7ffff7bc93d8 "./ogre/Components/Overlay/include/OgreFont.h", line=line@entry=256)
    at ./ogre/OgreMain/include/OgreException.h:266
#7  0x00007ffff7bc20e7 in Ogre::ExceptionFactory::throwException (code=code@entry=Ogre::Exception::ERR_DUPLICATE_ITEM, desc="Code point 67 not found in font SdkTrays/Caption", 
    src="getGlyphInfo", file=file@entry=0x7ffff7bc93d8 "./ogre/Components/Overlay/include/OgreFont.h", 
    line=line@entry=256) at ./ogre/OgreMain/include/OgreException.h:281
#8  0x00007ffff7bb8d29 in Ogre::Font::getGlyphInfo (id=67, this=0x555556446540)
    at ./ogre/Components/Overlay/include/OgreFont.h:255
#9  OgreBites::Widget::getCaptionWidth (caption="Click Me!", area=0x55555b93dbb0)
    at ./ogre/Components/Bites/src/OgreTrays.cpp:87
#10 0x00007ffff7bb8fe0 in OgreBites::Button::setCaption (this=0x55555b94a010, caption="Click Me!")
    at ./ogre/Components/Bites/src/OgreTrays.cpp:142
#11 0x00007ffff7bb919f in OgreBites::Button::Button (this=0x55555b94a010, name="MyButton", caption="Click Me!", width=0)
    at ./ogre/Components/Bites/src/OgreTrays.cpp:135
#12 0x00007ffff7bc098f in OgreBites::TrayManager::createButton (this=0x555557911cf0, trayLoc=OgreBites::TL_TOPLEFT, name="MyButton", caption="Click Me!", width=0)
    at ./ogre/Components/Bites/src/OgreTrays.cpp:1436
#13 0x000055555545380e in SceneLoadSample::setup (this=0x7fffffffd500)
    at ./DotSceneFormat/SceneLoader/src/main.cpp:365
#14 0x0000555555454e01 in main (argc=2, argv=0x7fffffffd8f8) at ./DotSceneFormat/SceneLoader/src/main.cpp:534
```
