### ISSUE TITLE
Segmentation fault on destruction of meshes loaded with Assimp

### ISSUE THREAD

**Issue by asherikov** [OGRECave/ogre#2797]
#### System Information
- Ogre Version: 13.6.2
- Operating System / Platform: Ubuntu 20.04

#### Detailled description

Segmentation fault on destruction of a mesh loaded with Assimp if an entity is created using it.
MWE (e.g., `a.out <path_to>/robot.mesh`, assimp does not support mesh format newer than 1.8):
```
#include <Ogre.h>
#include <OgreApplicationContext.h>
#include <Plugins/Assimp/OgreAssimpLoader.h>
 

int main(int /*argc*/, char **argv)
{                
    OgreBites::ApplicationContext context_;        
    Ogre::Root *root_;        
    Ogre::SceneManager *scene_manager_;        
            
            
    context_.initApp();            
    root_ = context_.getRoot();            
    scene_manager_ = root_->createSceneManager();            


    const std::string mesh_path = argv[1];                                                     
    Ogre::MeshPtr mesh = Ogre::MeshManager::getSingleton().createManual(                                                                                
            mesh_path, Ogre::ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME);
    Ogre::SkeletonPtr skeleton;
                                          
    Ogre::AssimpLoader loader;                               
    loader.load(mesh_path, mesh.get(), skeleton);

    Ogre::Entity *ent = scene_manager_->createEntity("LocalMesh_Ent", mesh);
                                    
    context_.closeApp();
                          
    return (EXIT_SUCCESS);
}
```

Backtrace
```
#0  0x0000555555677a40 in ?? ()
#1  0x00007ffff7e78384 in Ogre::VertexData::~VertexData (this=0x555556b950c0, __in_chrg=<optimized out>) at /ogre/OgreMain/src/OgreVertexIndexData.cpp:175
#2  0x00007ffff7e5e100 in Ogre::SubMesh::~SubMesh (this=0x555556a716d0, __in_chrg=<optimized out>) at /ogre/OgreMain/src/OgreSubMesh.cpp:48
#3  0x00007ffff7d3deb8 in Ogre::Mesh::unloadImpl (this=0x555556a4a410) at /ogre/OgreMain/src/OgreMesh.cpp:242                                                     
#4  0x00007ffff7dae6a9 in Ogre::Resource::unload (this=this@entry=0x555556a4a410) at /ogre/OgreMain/src/OgreResource.cpp:334                                                     
#5  0x00007ffff7d399bf in Ogre::Mesh::~Mesh (this=0x555556a4a410, __in_chrg=<optimized out>) at /ogre/OgreMain/src/OgreMesh.cpp:78                                                     
#6  0x00007ffff7d39cbd in Ogre::Mesh::~Mesh (this=0x555556a4a410, __in_chrg=<optimized out>) at /ogre/OgreMain/src/OgreMesh.cpp:74                                                     
#7  0x00005555555567e8 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555556b97050) at /usr/include/c++/9/bits/shared_ptr_base.h:148
#8  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555556b97050) at /usr/include/c++/9/bits/shared_ptr_base.h:148
#9  0x0000555555556535 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fffffffd248, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#10 std::__shared_ptr<Ogre::Mesh, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fffffffd240, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#11 std::shared_ptr<Ogre::Mesh>::~shared_ptr (this=0x7fffffffd240, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
#12 Ogre::SharedPtr<Ogre::Mesh>::~SharedPtr (this=0x7fffffffd240, __in_chrg=<optimized out>) at /include/OGRE/OgreSharedPtr.h:52 
```

**Comment by asherikov** [comment]
Thanks
