### ISSUE TITLE
[OGRE-141] Crash on Startup on OpenBSD

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#30]
<b>[reporter="pstumpf", created="Fri, 8 Feb 2013 11:35:53 +0100"]</b>

<p>SampleBrowser crashes on startup on OpenBSD; gdb backtrace with debug symbols, crashes somewhere in PCZSceneManager due to a NULL dereference <img class="emoticon" src="https://ogre3d.atlassian.net/images/icons/emoticons/help_16.png" height="16" width="16" align="absmiddle" alt="" border="0"/>:</p>

<p>#0  0x0000118ad5126b95 in Ogre::PCZSceneNode::getHomeZone (this=0x0)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/PlugIns/PCZSceneManager/src/OgrePCZSceneNode.cpp:135<br/>
#1  0x0000118ad5112903 in Ogre::PCZSceneManager::_findVisibleObjects (<br/>
    this=0x118ab2c3c000, cam=0x118ab4504800, visibleBounds=0x118abb49b828, <br/>
    onlyShadowCasters=false)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/PlugIns/PCZSceneManager/src/OgrePCZSceneManager.cpp:1229<br/>
#2  0x0000118ac1639c64 in Ogre::SceneManager::_renderScene (<br/>
    this=0x118ab2c3c000, camera=0x118ab4504800, vp=0x118abb49be00, <br/>
    includeOverlays=true)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreSceneManager.cpp:1479<br/>
#3  0x0000118ad5114b1a in Ogre::PCZSceneManager::_renderScene (<br/>
    this=0x118ab2c3c000, cam=0x118ab4504800, vp=0x118abb49be00, <br/>
    includeOverlays=true)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/PlugIns/PCZSceneManager/src/OgrePCZSceneManager.cpp:488<br/>
#4  0x0000118ac126303f in Ogre::Camera::_renderScene (this=0x118ab4504800, <br/>
    vp=0x118abb49be00, includeOverlays=true)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreCamera.cpp:427<br/>
#5  0x0000118ac179cf70 in Ogre::Viewport::update (this=0x118abb49be00)<br/>
--<del>Type <return> to continue, or q <return> to quit</del>--<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreViewport.cpp:224<br/>
#6  0x0000118ac15b1b94 in Ogre::RenderTarget::_updateViewport (<br/>
    this=0x118abb4a0a00, viewport=0x118abb49be00, updateStatistics=true)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreRenderTarget.cpp:200<br/>
#7  0x0000118ac15b1c81 in Ogre::RenderTarget::_updateAutoUpdatedViewports (<br/>
    this=0x118abb4a0a00, updateStatistics=true)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreRenderTarget.cpp:178<br/>
#8  0x0000118ac15af2ea in Ogre::RenderTarget::updateImpl (this=0x118abb4a0a00)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreRenderTarget.cpp:155<br/>
#9  0x0000118ac15aff38 in Ogre::RenderTarget::update (this=0x118abb4a0a00, <br/>
    swap=true)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreRenderTarget.cpp:613<br/>
#10 0x00001188b051f05f in OgreBites::SdkTrayManager::windowUpdate (<br/>
    this=0x118ab7581400) at SdkTrays.h:2816<br/>
#11 0x00001188b0532d99 in OgreBites::SdkTrayManager::resourceGroupScriptingStarted (this=0x118ab7581400, groupName=@0x118ab7c82810, scriptCount=93)<br/>
    at SdkTrays.h:2824<br/>
#12 0x0000118ac15c5778 in Ogre::ResourceGroupManager::fireResourceGroupScripting--<del>Type <return> to continue, or q <return> to quit</del>--<br/>
Started (this=0x118ab98b1f00, groupName=@0x118ab7c82810, scriptCount=93)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreResourceGroupManager.cpp:1369<br/>
#13 0x0000118ac15d08a5 in Ogre::ResourceGroupManager::parseResourceGroupScripts<br/>
    (this=0x118ab98b1f00, grp=0x118ab7c82800)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreResourceGroupManager.cpp:1053<br/>
#14 0x0000118ac15d13cc in Ogre::ResourceGroupManager::initialiseResourceGroup (<br/>
    this=0x118ab98b1f00, name=@0x7f7ffffdbde0)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/OgreMain/src/OgreResourceGroupManager.cpp:120<br/>
#15 0x00001188b054d1c2 in OgreBites::SampleBrowser::loadResources (<br/>
    this=0x7f7ffffdc010) at SampleBrowser.h:1127<br/>
#16 0x00001188b05516f8 in OgreBites::SampleBrowser::setup (this=0x7f7ffffdc010)<br/>
    at SampleBrowser.h:1044<br/>
#17 0x00001188b0552460 in OgreBites::SampleContext::initApp (<br/>
    this=0x7f7ffffdc010, initialSample=0x0) at SampleContext.h:273<br/>
#18 0x00001188b05541a9 in OgreBites::SampleContext::go (this=0x7f7ffffdc010, <br/>
    initialSample=0x0) at SampleContext.h:325<br/>
#19 0x00001188b051c882 in main (argc=1, argv=0x7f7ffffdc250)<br/>
    at /usr/ports/pobj/ogre_src_v1-8-1/ogre_src_v1-8-1/Samples/Browser/src/SampleBrowser.cpp:81</p>

<p>I can provide more info on demand.</p>

**Comment by paroj** [comment]
<b><i>[author="masterfalcon", created="Thu, 13 Jun 2013 08:35:49 +0200"]</i></b>
<p>Is this still an issue with 1.9?</p>

**Comment by paroj** [comment]
<b><i>[author="masterfalcon", created="Sat, 9 Nov 2013 06:43:57 +0100"]</i></b>
<p>If you have a chance to check this out with 1.9 that would be much appreciated. Thanks!</p>

**Comment by paroj** [comment]
<b><i>[author="spacegaier", created="Tue, 3 Mar 2015 20:54:12 +0100"]</i></b>
<p>I contacted the ticket owner regarding an update.</p>
